apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "hpp-dv"
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
      blank: {}
  storage:
    resources:
      requests:
        storage: 64Mi
    storageClassName: hostpath-provisioner
