apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: a-bridge-network  
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "a-bridge-network", 
    "type": "cnv-bridge", 
    "bridge": "br1"  
  }'
