apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: uploadvolume 
spec:
  source:
      upload: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
